import type { Portfolio, Position, Order, Trade, Broker, Strategy, RiskMetrics, MarketData } from '../types';

const currentTime = new Date().toISOString();

export const demoPortfolio: Portfolio = {
  totalValue: 125450.50,
  cashBalance: 25350.00,
  positionsValue: 100100.50,
  dailyPnL: 3250.75,
  dailyPnLPercent: 2.66,
  totalPnL: 12450.50,
  totalPnLPercent: 11.02,
  buyingPower: 150000.00,
  marginUsed: 35200.00,
  timestamp: currentTime,
};

export const demoPositions: Position[] = [
  {
    id: '1',
    symbol: 'AAPL',
    broker: 'alpaca',
    side: 'LONG',
    quantity: 100,
    avgPrice: 175.50,
    currentPrice: 178.25,
    marketValue: 17825.00,
    unrealizedPnL: 275.00,
    unrealizedPnLPercent: 1.57,
    timestamp: currentTime,
  },
  {
    id: '2',
    symbol: 'TSLA',
    broker: 'alpaca',
    side: 'LONG',
    quantity: 50,
    avgPrice: 245.00,
    currentPrice: 252.80,
    marketValue: 12640.00,
    unrealizedPnL: 390.00,
    unrealizedPnLPercent: 3.18,
    timestamp: currentTime,
  },
  {
    id: '3',
    symbol: 'MSFT',
    broker: 'ibkr',
    side: 'LONG',
    quantity: 75,
    avgPrice: 380.00,
    currentPrice: 378.50,
    marketValue: 28387.50,
    unrealizedPnL: -112.50,
    unrealizedPnLPercent: -0.39,
    timestamp: currentTime,
  },
  {
    id: '4',
    symbol: 'NVDA',
    broker: 'ibkr',
    side: 'LONG',
    quantity: 30,
    avgPrice: 495.00,
    currentPrice: 512.00,
    marketValue: 15360.00,
    unrealizedPnL: 510.00,
    unrealizedPnLPercent: 3.43,
    timestamp: currentTime,
  },
  {
    id: '5',
    symbol: 'BTC/USDT',
    broker: 'binance',
    side: 'LONG',
    quantity: 0.5,
    avgPrice: 42000.00,
    currentPrice: 43500.00,
    marketValue: 21750.00,
    unrealizedPnL: 750.00,
    unrealizedPnLPercent: 3.57,
    timestamp: currentTime,
  },
];

export const demoOrders: Order[] = [
  {
    id: '1',
    symbol: 'AAPL',
    broker: 'alpaca',
    type: 'LIMIT',
    side: 'BUY',
    quantity: 100,
    price: 177.50,
    status: 'ACTIVE',
    timeInForce: 'GTC',
    createdAt: currentTime,
    updatedAt: currentTime,
  },
  {
    id: '2',
    symbol: 'TSLA',
    broker: 'alpaca',
    type: 'STOP',
    side: 'SELL',
    quantity: 50,
    stopPrice: 240.00,
    status: 'ACTIVE',
    timeInForce: 'GTC',
    createdAt: currentTime,
    updatedAt: currentTime,
  },
  {
    id: '3',
    symbol: 'BTC/USDT',
    broker: 'binance',
    type: 'MARKET',
    side: 'BUY',
    quantity: 0.1,
    status: 'FILLED',
    filledQuantity: 0.1,
    averageFillPrice: 43500.00,
    timeInForce: 'IOC',
    createdAt: currentTime,
    updatedAt: currentTime,
  },
];

export const demoTrades: Trade[] = [
  {
    id: '1',
    orderId: '3',
    symbol: 'AAPL',
    broker: 'alpaca',
    side: 'BUY',
    quantity: 50,
    price: 178.25,
    commission: 0.50,
    pnl: 0,
    timestamp: currentTime,
  },
  {
    id: '2',
    orderId: '4',
    symbol: 'TSLA',
    broker: 'alpaca',
    side: 'SELL',
    quantity: 25,
    price: 252.80,
    commission: 0.25,
    pnl: 195.00,
    timestamp: currentTime,
  },
];

export const demoBrokers: Broker[] = [
  {
    id: 'binance',
    name: 'binance',
    displayName: 'Binance',
    status: 'connected',
    accountType: 'live',
    balance: 45250.00,
    positionsCount: 3,
    ordersCount: 2,
    lastSync: currentTime,
  },
  {
    id: 'ibkr',
    name: 'ibkr',
    displayName: 'Interactive Brokers',
    status: 'connected',
    accountType: 'live',
    balance: 62100.50,
    positionsCount: 7,
    ordersCount: 5,
    lastSync: currentTime,
  },
  {
    id: 'alpaca',
    name: 'alpaca',
    displayName: 'Alpaca Markets',
    status: 'connected',
    accountType: 'paper',
    balance: 18100.00,
    positionsCount: 2,
    ordersCount: 3,
    lastSync: currentTime,
  },
];

export const demoStrategies: Strategy[] = [
  {
    id: '1',
    name: 'Momentum Swing',
    description: 'Identifies momentum shifts using RSI and MACD indicators',
    status: 'active',
    type: 'momentum',
    broker: 'alpaca',
    symbols: ['AAPL', 'TSLA', 'MSFT'],
    totalPnL: 2350.00,
    dailyPnL: 125.50,
    totalTrades: 45,
    winRate: 67.8,
    sharpeRatio: 1.92,
    maxDrawdown: 3.2,
    createdAt: currentTime,
    updatedAt: currentTime,
  },
  {
    id: '2',
    name: 'Mean Reversion',
    description: 'Trades overbought/oversold conditions with Bollinger Bands',
    status: 'active',
    type: 'mean_reversion',
    broker: 'ibkr',
    symbols: ['NVDA', 'AMD', 'INTC'],
    totalPnL: 1850.50,
    dailyPnL: 85.25,
    totalTrades: 38,
    winRate: 71.1,
    sharpeRatio: 2.15,
    maxDrawdown: 2.5,
    createdAt: currentTime,
    updatedAt: currentTime,
  },
  {
    id: '3',
    name: 'Pairs Trading',
    description: 'Statistical arbitrage between correlated assets',
    status: 'paused',
    type: 'pairs',
    broker: 'binance',
    symbols: ['BTC/USDT', 'ETH/USDT'],
    totalPnL: -450.00,
    dailyPnL: -85.00,
    totalTrades: 22,
    winRate: 45.5,
    sharpeRatio: 0.85,
    maxDrawdown: 5.8,
    createdAt: currentTime,
    updatedAt: currentTime,
  },
];

export const demoRiskMetrics: RiskMetrics = {
  portfolioValue: 125450.50,
  currentDrawdown: 2.3,
  maxDrawdown: 5.8,
  sharpeRatio: 1.85,
  sortinoRatio: 2.12,
  winRate: 65.2,
  profitFactor: 1.92,
  dailyVaR: 3450.00,
  weeklyVaR: 8920.00,
  positionConcentration: 0.23,
  leverageRatio: 1.35,
  timestamp: currentTime,
};

export const demoMarketData: MarketData[] = [
  {
    symbol: 'AAPL',
    price: 178.25,
    bid: 178.24,
    ask: 178.26,
    volume: 52341200,
    change: 2.75,
    changePercent: 1.57,
    high: 179.50,
    low: 176.80,
    timestamp: currentTime,
  },
  {
    symbol: 'TSLA',
    price: 252.80,
    bid: 252.75,
    ask: 252.85,
    volume: 98234100,
    change: 7.80,
    changePercent: 3.18,
    high: 255.20,
    low: 248.50,
    timestamp: currentTime,
  },
];
